(function(){
'use strict';
document.addEventListener('DOMContentLoaded',function(){
    const session=window.checkAuth(); if(!session)return;
    const form=document.getElementById('dprForm'),steps=[...document.querySelectorAll('.form-step')],stepItems=[...document.querySelectorAll('#stepList li')];
    const previous=document.getElementById('previousStep'),next=document.getElementById('nextStep'),submit=document.getElementById('submitDpr');
    const fileInput=document.getElementById('fileInput'),fileList=document.getElementById('fileList'),dropZone=document.getElementById('dropZone');
    const draftKey=`dpr_draft_${session.email}`,required=[...form.querySelectorAll('[required]')]; let current=0,files=[];
    document.getElementById('currentUserName').textContent=session.name||session.email;
    document.getElementById('currentUserRole').textContent=(session.role||'project officer').replaceAll('_',' ');
    document.getElementById('userInitial').textContent=(session.name||session.email).charAt(0).toUpperCase();

    function showStep(index){current=Math.max(0,Math.min(index,steps.length-1));steps.forEach((s,i)=>s.classList.toggle('active',i===current));stepItems.forEach((s,i)=>s.classList.toggle('active',i===current));previous.hidden=current===0;next.hidden=current===steps.length-1;submit.hidden=current!==steps.length-1;window.scrollTo({top:0,behavior:'smooth'});}
    function validateStep(){const fields=[...steps[current].querySelectorAll('[required]')];let valid=true;fields.forEach(field=>{field.classList.add('touched');if(!field.checkValidity())valid=false;});if(!valid){fields.find(f=>!f.checkValidity())?.focus();return false;}stepItems[current].classList.add('complete');return true;}
    function updateCompletion(){const complete=required.filter(f=>f.type==='checkbox'?f.checked:String(f.value).trim()).length;const percent=Math.round(complete/required.length*100);document.getElementById('completionText').textContent=`${percent}%`;document.getElementById('completionBar').style.width=`${percent}%`;}
    function draftData(){const data={};new FormData(form).forEach((value,key)=>{if(!(value instanceof File))data[key]=value;});return data;}
    function saveDraft(showFeedback=true){localStorage.setItem(draftKey,JSON.stringify({data:draftData(),updatedAt:new Date().toISOString()}));document.getElementById('saveStatus').textContent='Draft saved';document.getElementById('saveTime').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if(showFeedback){const btn=document.getElementById('saveDraft');const old=btn.innerHTML;btn.innerHTML='<span class="material-icons">check</span> Saved';setTimeout(()=>btn.innerHTML=old,1200);}}
    function restoreDraft(){try{const draft=JSON.parse(localStorage.getItem(draftKey));if(!draft)return;Object.entries(draft.data||{}).forEach(([name,value])=>{const field=form.elements[name];if(!field)return;if(field.length&&!field.tagName){[...field].forEach(item=>item.checked=Array.isArray(value)?value.includes(item.value):item.value===value);}else if(field.type==='checkbox')field.checked=value==='on';else field.value=value;});document.getElementById('saveTime').textContent=`Last saved ${new Date(draft.updatedAt).toLocaleString()}`;}catch(_){}updateCompletion();}
    function addFiles(list){const validExt=/\.(pdf|xlsx?|docx?|jpe?g|png)$/i;[...list].forEach(file=>{if(file.size>50*1024*1024||!validExt.test(file.name)){showMessage(`${file.name} is not an accepted file.`, 'error');return;}if(!files.some(f=>f.name===file.name&&f.size===file.size))files.push(file);});renderFiles();}
    function renderFiles(){fileList.innerHTML=files.map((file,i)=>`<div class="file-item"><span><span class="material-icons">insert_drive_file</span><span><strong>${escapeHtml(file.name)}</strong><br>${(file.size/1048576).toFixed(2)} MB</span></span><button type="button" data-remove="${i}" aria-label="Remove ${escapeHtml(file.name)}"><span class="material-icons">delete</span></button></div>`).join('');}
    function escapeHtml(value){const div=document.createElement('div');div.textContent=value;return div.innerHTML;}
    function showMessage(text,type){const box=document.getElementById('formMessage');box.textContent=text;box.className=`form-message ${type}`;}
    next.addEventListener('click',()=>{if(validateStep()){saveDraft(false);showStep(current+1);}});previous.addEventListener('click',()=>showStep(current-1));stepItems.forEach((item,i)=>item.addEventListener('click',()=>{if(i<=current||validateStep())showStep(i);}));
    form.addEventListener('input',()=>{updateCompletion();document.getElementById('saveStatus').textContent='Unsaved changes';});document.getElementById('saveDraft').addEventListener('click',()=>saveDraft());
    document.getElementById('selectFilesButton').addEventListener('click',()=>fileInput.click());fileInput.addEventListener('change',e=>addFiles(e.target.files));
    ['dragenter','dragover'].forEach(event=>dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.add('dragover');}));['dragleave','drop'].forEach(event=>dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.remove('dragover');}));dropZone.addEventListener('drop',e=>addFiles(e.dataTransfer.files));dropZone.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fileInput.click();}});fileList.addEventListener('click',e=>{const button=e.target.closest('[data-remove]');if(button){files.splice(Number(button.dataset.remove),1);renderFiles();}});
    form.addEventListener('submit',e=>{e.preventDefault();let invalidStep=steps.findIndex(step=>[...step.querySelectorAll('[required]')].some(field=>!field.checkValidity()));if(invalidStep>=0){showStep(invalidStep);validateStep();showMessage('Complete all required fields before submission.','error');return;}const record={id:`DPR-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`,submittedAt:new Date().toISOString(),submittedBy:session.email,status:'Submitted for appraisal',data:draftData(),documents:files.map(f=>({name:f.name,size:f.size,type:f.type}))};const submissions=JSON.parse(localStorage.getItem('dpr_submissions')||'[]');submissions.unshift(record);localStorage.setItem('dpr_submissions',JSON.stringify(submissions));localStorage.removeItem(draftKey);showMessage(`${record.id} submitted successfully for appraisal.`,'success');submit.disabled=true;submit.innerHTML='<span class="material-icons">check_circle</span> Submitted';window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});});
    const start=document.getElementById('startDate'),end=document.getElementById('endDate'),duration=document.getElementById('duration');function calculateDuration(){if(start.value&&end.value){const months=Math.ceil((new Date(end.value)-new Date(start.value))/(1000*60*60*24*30.44));if(months>0)duration.value=months;updateCompletion();}}start.addEventListener('change',calculateDuration);end.addEventListener('change',calculateDuration);
    restoreDraft();showStep(0);setInterval(()=>saveDraft(false),30000);
});
}());
